"""Kiyomi "Know Me" Profile Card — A living document of who you are.

Generates a beautiful, shareable profile card that combines everything
Kiyomi knows: identity, family, goals, health, finances, habits, preferences.

Export as formatted text (Telegram) or PDF.
Share with your doctor, financial advisor, or spouse.

This is the "wow" moment in demos.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger("kiyomi.profile")

CONFIG_DIR = Path.home() / ".kiyomi"
MEMORY_DIR = CONFIG_DIR / "memory"


def generate_profile_card(config: dict) -> str:
    """Generate the full "Know Me" profile card.
    
    Pulls from every data source Kiyomi has:
    - Memory (identity, family, preferences)
    - Health skill
    - Financial data
    - Habits
    - Relationships
    - Tasks/Goals
    
    Returns formatted markdown string.
    """
    name = config.get("name", "User")
    now = datetime.now()
    
    sections = []
    
    # ── Header ──
    sections.append(f"# 🪪 Know Me — {name}'s Profile")
    sections.append(f"*Generated by Kiyomi on {now.strftime('%B %d, %Y at %I:%M %p')}*\n")
    
    # ── Identity ──
    identity = _get_identity_section(config)
    if identity:
        sections.append(identity)
    
    # ── My People ──
    people = _get_people_section()
    if people:
        sections.append(people)
    
    # ── Health Snapshot ──
    health = _get_health_section()
    if health:
        sections.append(health)
    
    # ── Financial Snapshot ──
    financial = _get_financial_section(config)
    if financial:
        sections.append(financial)
    
    # ── Habits & Streaks ──
    habits = _get_habits_section()
    if habits:
        sections.append(habits)
    
    # ── Goals & Tasks ──
    goals = _get_goals_section()
    if goals:
        sections.append(goals)
    
    # ── Preferences ──
    prefs = _get_preferences_section()
    if prefs:
        sections.append(prefs)
    
    # ── Fun Facts ──
    fun = _get_fun_facts_section()
    if fun:
        sections.append(fun)
    
    # ── Footer ──
    sections.append("\n---")
    sections.append(f"*Powered by Kiyomi — Your Personal AI Assistant*")
    sections.append(f"*{len(sections)} sections • Updated in real-time*")
    
    return "\n\n".join(sections)


def generate_compact_card(config: dict) -> str:
    """Generate a compact version for Telegram (< 4000 chars)."""
    name = config.get("name", "User")
    now = datetime.now()
    
    lines = [
        f"🪪 **{name}'s Profile Card**",
        f"_Updated {now.strftime('%b %d, %Y')}_\n",
    ]
    
    # Identity quick hits
    identity_facts = _load_memory_category("identity")
    if identity_facts:
        lines.append("👤 **About Me**")
        for fact in identity_facts[:5]:
            lines.append(f"  • {fact}")
        lines.append("")
    
    # People
    try:
        from skills.relationships import get_relationships_skill
        rs = get_relationships_skill()
        people = rs.get_all_people()[:5]
        if people:
            lines.append("👥 **My People**")
            for p in people:
                rel = p.get("relationship", "")
                bday = f" 🎂 {p.get('birthday', '')}" if p.get("birthday") else ""
                lines.append(f"  • {p['name']} ({rel}){bday}")
            lines.append("")
    except (ImportError, Exception):
        pass
    
    # Health quick stats
    try:
        from skills.health import HealthSkill
        hs = HealthSkill()
        data = hs.load_data()
        if data.get("medications") or data.get("vitals") or data.get("symptoms"):
            lines.append("💊 **Health**")
            for m in data.get("medications", [])[:3]:
                lines.append(f"  • {m.get('name', '')} — {m.get('dosage', '')}")
            for v in data.get("vitals", [])[-2:]:
                lines.append(f"  • {v.get('type', '')}: {v.get('value', '')}")
            lines.append("")
    except (ImportError, Exception):
        pass
    
    # Financial snapshot
    try:
        from plaid_integration import is_bank_connected, get_balances
        if is_bank_connected():
            plaid_cfg = config.get("plaid", {})
            bal = get_balances(
                plaid_cfg.get("client_id", ""),
                plaid_cfg.get("secret", ""),
                plaid_cfg.get("env", "sandbox"),
            )
            if "error" not in bal:
                lines.append(f"💰 **Net Worth:** ${bal['net_worth']:,.2f}")
                for a in bal["accounts"][:3]:
                    lines.append(f"  • {a['name']}: ${a['balance']:,.2f}")
                lines.append("")
    except (ImportError, Exception):
        pass
    
    # Habits
    try:
        from skills.habits import get_habits_skill
        hs = get_habits_skill()
        status = hs.get_today_status()
        if "No habits" not in status:
            lines.append("🏋️ **Habits**")
            # Just show the summary line
            for line in status.split("\n"):
                if "Progress" in line or "✅" in line or "⬜" in line:
                    lines.append(f"  {line.strip()}")
            lines.append("")
    except (ImportError, Exception):
        pass
    
    # Goals
    try:
        from skills.tasks import TaskSkill
        ts = TaskSkill()
        tasks = ts.get_open_tasks()
        if tasks:
            lines.append(f"📋 **Tasks** ({len(tasks)} pending)")
            for t in tasks[:3]:
                lines.append(f"  • {t.get('text', t.get('title', ''))[:50]}")
            lines.append("")
    except (ImportError, Exception):
        pass
    
    # Preferences
    pref_facts = _load_memory_category("preferences")
    if pref_facts:
        lines.append("⭐ **Preferences**")
        for fact in pref_facts[:5]:
            lines.append(f"  • {fact}")
        lines.append("")
    
    lines.append("─" * 25)
    lines.append("_Powered by Kiyomi_ 💛")
    
    return "\n".join(lines)


def generate_doctor_card(config: dict) -> str:
    """Generate a health-focused card to share with a doctor."""
    name = config.get("name", "User")
    
    lines = [
        f"🏥 **Health Profile — {name}**",
        f"_Generated {datetime.now().strftime('%b %d, %Y')}_\n",
    ]
    
    # Identity basics
    identity_facts = _load_memory_category("identity")
    if identity_facts:
        lines.append("**Patient Info:**")
        for fact in identity_facts:
            if any(kw in fact.lower() for kw in ["age", "born", "blood", "allerg", "height", "weight"]):
                lines.append(f"  • {fact}")
        lines.append("")
    
    # Health data
    try:
        from skills.health import HealthSkill
        hs = HealthSkill()
        data = hs.load_data()
        
        # Medications
        meds = data.get("medications", [])
        if meds:
            lines.append("**Current Medications:**")
            for m in meds:
                lines.append(f"  • {m.get('name', '')} — {m.get('dosage', '')} ({m.get('frequency', '')})")
            lines.append("")
        
        # Recent vitals
        vitals = data.get("vitals", [])
        if vitals:
            lines.append("**Recent Vitals:**")
            for v in vitals[-5:]:
                lines.append(f"  • {v.get('date', '')}: {v.get('type', '')} — {v.get('value', '')}")
            lines.append("")
        
        # Conditions/symptoms
        symptoms = data.get("symptoms", [])
        if symptoms:
            lines.append("**Recent Symptoms:**")
            for s in symptoms[-5:]:
                lines.append(f"  • {s.get('date', '')}: {s.get('description', '')}")
            lines.append("")
    except (ImportError, Exception):
        pass
    
    # Health-related memory
    health_facts = _load_memory_category("health")
    if health_facts:
        lines.append("**Health Notes:**")
        for fact in health_facts:
            lines.append(f"  • {fact}")
        lines.append("")
    
    lines.append("─" * 25)
    lines.append("_Generated by Kiyomi AI Assistant_")
    
    return "\n".join(lines)


# ── Internal helpers ──

def _load_memory_category(category: str) -> list[str]:
    """Load facts from a memory category file."""
    cat_file = MEMORY_DIR / f"{category}.md"
    if not cat_file.exists():
        return []
    
    facts = []
    for line in cat_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and not line.startswith("["):
            # Extract the fact part (after timestamp if present)
            if "] " in line:
                line = line.split("] ", 1)[-1]
            facts.append(line)
    
    return facts


def _get_identity_section(config: dict) -> str:
    """Build identity section."""
    facts = _load_memory_category("identity")
    if not facts:
        return ""
    
    lines = ["## 👤 About Me\n"]
    for fact in facts[:10]:
        lines.append(f"• {fact}")
    return "\n".join(lines)


def _get_people_section() -> str:
    """Build people section."""
    try:
        from skills.relationships import get_relationships_skill
        rs = get_relationships_skill()
        people = rs.get_all_people()
        if not people:
            return ""
        
        lines = ["## 👥 My People\n"]
        for p in people[:10]:
            rel = p.get("relationship", "unknown")
            emoji = {
                "wife": "💕", "husband": "💕", "partner": "💕",
                "mom": "👩", "dad": "👨",
                "brother": "👦", "sister": "👧",
                "son": "👦", "daughter": "👧",
                "friend": "🤝", "boss": "💼",
            }.get(rel, "👤")
            
            line = f"{emoji} **{p['name']}** — {rel.capitalize()}"
            if p.get("birthday"):
                line += f" (🎂 {p['birthday']})"
            lines.append(line)
            
            for fact in p.get("facts", [])[:2]:
                lines.append(f"  _{fact}_")
        
        return "\n".join(lines)
    except (ImportError, Exception):
        return ""


def _get_health_section() -> str:
    """Build health section."""
    try:
        from skills.health import HealthSkill
        hs = HealthSkill()
        data = hs.load_data()
        
        lines = ["## 💊 Health\n"]
        
        meds = data.get("medications", [])
        if meds:
            lines.append("**Medications:**")
            for m in meds[:5]:
                lines.append(f"• {m.get('name', '')} — {m.get('dosage', '')}")
        
        vitals = data.get("vitals", [])
        if vitals:
            lines.append("\n**Recent Vitals:**")
            for v in vitals[-3:]:
                lines.append(f"• {v.get('type', '')}: {v.get('value', '')} ({v.get('date', '')})")
        
        if len(lines) <= 1:
            return ""
        return "\n".join(lines)
    except (ImportError, Exception):
        return ""


def _get_financial_section(config: dict) -> str:
    """Build financial section."""
    try:
        from plaid_integration import is_bank_connected, get_balances, spending_summary
        if not is_bank_connected():
            return ""
        
        plaid_cfg = config.get("plaid", {})
        cid = plaid_cfg.get("client_id", "")
        secret = plaid_cfg.get("secret", "")
        env = plaid_cfg.get("env", "sandbox")
        
        lines = ["## 💰 Finances\n"]
        
        bal = get_balances(cid, secret, env)
        if "error" not in bal:
            lines.append(f"**Net Worth:** ${bal['net_worth']:,.2f}\n")
            for a in bal["accounts"]:
                lines.append(f"• {a['name']}: ${a['balance']:,.2f}")
        
        return "\n".join(lines)
    except (ImportError, Exception):
        return ""


def _get_habits_section() -> str:
    """Build habits section."""
    try:
        from skills.habits import get_habits_skill
        hs = get_habits_skill()
        
        if not hs.data.get("habits"):
            return ""
        
        lines = ["## 🏋️ Habits & Streaks\n"]
        
        for habit in hs.data["habits"]:
            if not habit.get("active", True):
                continue
            streak = hs._get_streak(habit["key"])
            fire = "🔥" * min(streak // 7, 5) if streak >= 7 else ""
            lines.append(f"• **{habit['name']}** — {streak}-day streak {fire}")
        
        report = hs.get_weekly_report()
        if report:
            lines.append(f"\n{report}")
        
        return "\n".join(lines)
    except (ImportError, Exception):
        return ""


def _get_goals_section() -> str:
    """Build goals section."""
    try:
        from skills.tasks import TaskSkill
        ts = TaskSkill()
        data = ts.load_data()
        
        open_tasks = ts.get_open_tasks()
        all_tasks = data.get("tasks", data.get("items", []))
        completed = [t for t in all_tasks if t.get("done") or t.get("completed")]
        
        if not open_tasks and not completed:
            return ""
        
        lines = ["## 📋 Goals & Tasks\n"]
        
        if open_tasks:
            lines.append(f"**Active ({len(open_tasks)}):**")
            for t in open_tasks[:10]:
                text = t.get('text', t.get('title', ''))
                due = f" (due: {t.get('due', '')})" if t.get("due") else ""
                lines.append(f"• {text}{due}")
        
        if completed:
            lines.append(f"\n**Recently Completed ({len(completed)}):**")
            for t in completed[-5:]:
                text = t.get('text', t.get('title', ''))
                lines.append(f"• ~~{text}~~ ✅")
        
        return "\n".join(lines)
    except (ImportError, Exception):
        return ""


def _get_preferences_section() -> str:
    """Build preferences section."""
    facts = _load_memory_category("preferences")
    if not facts:
        return ""
    
    lines = ["## ⭐ Preferences\n"]
    for fact in facts[:15]:
        lines.append(f"• {fact}")
    return "\n".join(lines)


def _get_fun_facts_section() -> str:
    """Build fun facts from various memory categories."""
    other_facts = _load_memory_category("other")
    work_facts = _load_memory_category("work")
    
    facts = []
    if other_facts:
        facts.extend(other_facts[:5])
    if work_facts:
        facts.extend(work_facts[:5])
    
    if not facts:
        return ""
    
    lines = ["## 🎯 Notes & Fun Facts\n"]
    for fact in facts[:10]:
        lines.append(f"• {fact}")
    return "\n".join(lines)
